### ISSUE TITLE
Can't run with babel 6

### ISSUE THREAD

**Issue by hank7444** [vladpalos/babel-plugin-remove-decorators#3]
![image](https://cloud.githubusercontent.com/assets/4727090/12547442/710a80aa-c38b-11e5-8bc3-3b52b3c14368.png)

**Comment by geraldfullam** [comment]
I'm having similar errors:

```
/Users/.../Sites/react/kanban/node_modules/babel-core/lib/api/node.js:78
  throw new Error("The (" + alias + ") Babel 5 plugin is being run with Babel 6.");
  ^

Error: The (remove-decorators) Babel 5 plugin is being run with Babel 6.
    at new Plugin (/Users/.../Sites/react/kanban/node_modules/babel-core/lib/api/node.js:78:9)
    at exports.default (/Users/.../Sites/react/kanban/node_modules/babel-plugin-remove-decorators/lib/index.js:11:10)
```

<img width="856" alt="screen shot 2016-05-06 at 9 20 34 am" src="https://cloud.githubusercontent.com/assets/5685540/15074442/07899468-136d-11e6-995d-0a8397cbc63c.png">

**Comment by arkadeloyalty** [comment]
@vladpalos any update or suggestion for this?

**Comment by Vivekbhusal** [comment]
@hank7444 @geraldfullam How did you resolve this?

**Comment by nikordaris** [comment]
For those who struggled finding a plugin for this like me, @ldabiralai seems to have figured it out at his [babel-plugin-remove-decorator](https://github.com/ldabiralai/babel-plugin-remove-decorator).
